### ISSUE TITLE
[Fix] Ids can be changed to UUIDs

### ISSUE THREAD

**Issue by WoLfulus** [directus/api-next#152]
- Makes it easier to rollback migrations that inserts data into the database
- Makes it easier to update specific rows on migrations
- Future proof

**Comment by WoLfulus** [comment]
@rijkvanzanten

**Comment by WoLfulus** [comment]
We thought about this when creating the migrations. Having IDs as UUID makes it easier to make sure there are fields we are managing inside directus code, by not relying on sequential ids.

As an example:

- [directus] migration creates initial fields, ids are not at 169
- [user] user adds a field on one of his table, id is now 170
- [directus] migration adds a new field, id is not at 171

If user wants to rollback a directus version, there's no way we can reliably remove that entry added on the second migration. The same happen if in a future migration we need to change a value/interface/whatever in a specific system field.

This might be applied in all system tables too.

Note: until there's a decision on this, there's no way to rollback migrations and we'll just throw an exception on `down()`

**Comment by rijkvanzanten** [comment]
I'm absolutely in favor of this. Do we want to go with UUID or UID?

It would be nice if we can have a short(er) unique ID in the context of the table instead of globally?

UUIDs can be very long: `/:project/fields/81739554-96e4-4a02-a877-c776b1de2a0e`

**Comment by WoLfulus** [comment]
I'm not familiar with how UID works, and I need to check the collision rate. 

I was personally thinking on using UUID.

**Comment by rijkvanzanten** [comment]
Depends on the character set we support. UUID only uses `[-a-z0-9]`, by using `[_-a-zA-Z0-9]` we can reduce the size from 36 to ~20 characters.

I'm fine with defaulting to UUID for these, but it would be nice if we could look into smaller alternatives

**Comment by arcifius** [comment]
Worth mentioning that UUIDs, in some databases, can receive a great query boost and can be stored as raw binary... UIDs will be stored as strings and won't share optimisation features

**Comment by WoLfulus** [comment]
We'll use UUIDs, but it would be nice to have surrogate keys for smaller api searches. We need to research this later.

**Comment by WoLfulus** [comment]
Done

**Comment by westhouseit** [comment]
Just for reference since I'm doing some performance testing:

Switching from bigint autoincrement to char uuid PK results an average of 100% increase in select time from 1.6ms -> 3.1ms on a 250k row table.

Obviously this is only one case and a lot more testing would be needed. With more memory available for indexes the difference could be reduced to zero.

The cost is likely worth it considering the comments in this issue and there are likely better areas to focus optimization.

**Comment by benhaynes** [comment]
We're switching to UUIDs for all system data in v9... so this sounds promising, especially for things like `directus_activity` where we can easily have 100k+ records.

**Comment by westhouseit** [comment]
In my case I tested on directus_files using a common query that was stupidly slow on v8. Since the cast to char shouldn't be needed on v9 the performance loss of uuid vs int pk shouldn't be noticed. There are some optimizations that could be considered, but I wouldn't spend time on them unless there's no other "low-hanging fruit" to pluck. ;-)
