### ISSUE TITLE
[Review] Custom migration command for Directus

### ISSUE THREAD

**Issue by WoLfulus** [directus/api-next#159]
Running migrations in laravel using the `loadMigrationsFrom` have some troubles. For example, if we configure the system database to live under `system` and user database to live under `user`, the migrations table is created in `user` database. Once we do a `migration:fresh` for example, the migration system won't clear the system database tables and migration will fail.

The idea is to extend the current console commands from laravel (targeting a proper migration table with its prefix + the connection information) to enable the usage of commands like 

`directus:migrate:fresh`

We then remove the `loadMigrationsFrom` from the provider and directus migrations will only execute migrations from Directus itself.

**Comment by WoLfulus** [comment]
@jooola do you think this is possible? I'm placing a test command into the repository soon

**Comment by jooola** [comment]
Sorry, could you clarify:

(`migrate` could also be `fresh`, since we need to be consistent)

`artisan db:migrate` runs the user migrations ?
`artisan directus:db:migrate` runs the directus system migration ?

Or will `directus:db:migrate` handle both migrations automatically ?

I think extending the existing migration command is pretty easy.
But we have many ways to fix this:
- having 2 commands
- extending the existing command with options and more logic
- leave existing migrate command for user data, and add a directus command for system data

Which one is preferred ?

**Comment by WoLfulus** [comment]
I got this one today.

Ended up implementing.

- `php artisan directus:install` (migrate up, no check for migrations table existence) 
- `php artisan directus:upgrade` (migrate up, check for migrations table existence) 
- `php artisan directus:upgrade --rollback` (migrate down, check for migrations table existence)
